config/routes.rb
Rails.application.routes.draw do

  root 'users/homes#top'

  devise_for :admins, controllers: {
    sessions: "admins/sessions"
  }
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }

  namespace :admins do
    resources :products, only: [:index, :edit, :update, :destroy]
    get '', to: 'products#top'
    resources :genres, only: [:index, :create, :edit, :update]
    resources :reviews, only: [:index, :update]
    resources :users, only: [:index, :show, :edit, :update]
    get "products_search/:id", to: "products#search", as:"products_search"
  end

  namespace :users do
    resources :buy_lists, only: [:index, :show, :create, :update, :destroy]
    resources :buy_list_products, only: [:create, :update, :destroy]
    resources :products, only: [:new, :index, :show, :edit, :create, :update, :destroy] do
      resource :favorites, only: [:create, :destroy]
    end
    resources :reviews, only: [:create, :destroy]
    resources :users, only: [:show, :edit, :update]
    resources :favorites, only: [:index]
    get "guide", to: 'homes#guide'
  end


end

app/models/buy_list.rb
class BuyList < ApplicationRecord

  belongs_to :user
  has_many :buy_list_products, dependent: :destroy

  # ユーザーが作成できる買い物リスト名は空欄にできない + 一意性を設定
  validates :title, presence: true, uniqueness: { scope: :user_id }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

  has_many :buy_lists, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :products, dependent: :destroy
  attachment :image

  validates :name, presence: true
  validates :name_kana, presence: true,
                format: {
                  with: /\A[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+\z/,
                  message: "は全角カタカナのみで入力して下さい"
                }
  validates :nickname, presence: true

end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :authenticate_admin!

  def index
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true).page(params[:page]).per(20)
  end

  def edit
    @reviews = @user.reviews.all.page(params[:page]).per(20)
  end

  def update
    @user.update(user_params)
    redirect_to admins_users_path(@user), notice:"会員ステータスが変更されました"
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:user_id, :status)
  end

end

app/controllers/users/buy_list_products_controller.rb
class Users::BuyListProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_buy_list_product, only: [:edit, :update, :destroy]

  def create
    @buy_list_product = BuyListProduct.new(buy_list_product_params)
    @buy_list_product.save
    flash[:notice] = "買い物リストに追加しました"
    redirect_back(fallback_location: root_path)
  end

  def update
    dead_line = @buy_list_product.dead_line
    if params[:buy_list_product][:cost].present?
      update_dead_line = dead_line + ((params[:buy_list_product][:cost].to_i * params[:buy_list_product][:amount].to_i).days)
    else
      update_dead_line = Date.today
    end
    new_buy_list_product_params = buy_list_product_params
    new_buy_list_product_params[:dead_line] = update_dead_line
    @buy_list_product.update(new_buy_list_product_params)
    # 元のページへリダイレクト
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @buy_list_product.destroy
    flash[:notice] = "買い物リストを削除しました"
    redirect_back(fallback_location: root_path)
  end

  private

  def set_buy_list_product
    @buy_list_product = BuyListProduct.find(params[:id])
  end

  def buy_list_product_params
    params.require(:buy_list_product).permit(:buy_list_id, :product_id, :amount, :cost, :dead_line)
  end

end

app/controllers/users/buy_lists_controller.rb
class Users::BuyListsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_buy_list, only: [:show, :update, :destroy]

  def index
    @new_buy_list = BuyList.new
    @buy_lists = current_user.buy_lists.all
  end

  def show
    @buy_list = BuyList.find(params[:id])
    @buy_list_products = @buy_list.buy_list_products.all
  end

  def create
    @new_buy_list = current_user.buy_lists.new(buy_list_params)
    if @new_buy_list.save
      redirect_to users_buy_lists_path, notice: "買い物リスト　#{@new_buy_list.title}を作成しました"
    else
      @buy_lists = current_user.buy_lists.all
      render "index"
    end

  end

  def update
    if @buy_list.update(buy_list_params)
      redirect_to users_buy_list_path(@buy_list), notice: "買い物リスト名を変更しました"
    else
      render "show"
    end

  end

  def destroy
    @buy_list.destroy
    redirect_to users_buy_lists_path, notice: "買い物リストを削除しました"
  end

  private

  def buy_list_params
    params.require(:buy_list).permit(:user_id, :title)
  end

  def set_buy_list
    @buy_list = BuyList.find(params[:id])
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/favorites_controller.rb
class Users::FavoritesController < ApplicationController
  before_action :authenticate_user!

  def index
    @favorites = current_user.favorites.page(params[:page]).per(20)
  end

  def create
    @product = Product.find(params[:product_id])
    favorite = current_user.favorites.new(product_id: @product.id)
    favorite.save
  end

  def destroy
    @product = Product.find(params[:product_id])
    @favorites = current_user.favorites.page(params[:page]).per(20)
    favorite = current_user.favorites.find_by(product_id: @product.id)
    favorite.destroy
  end

end

app/controllers/users/homes_controller.rb
class Users::HomesController < ApplicationController
  def top

  end

  def guide

  end

end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/products_controller.rb
class Users::ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_search
  before_action :set_user, only: [:edit, :update, :destroy]

  def top

  end

  def new
    @product = Product.new
  end

  def index
    @products = @q.result(distinct: true).page(params[:page]).per(12)
    @products_count = @q.result(distinct: true).count
  end

  def show
    @product = Product.find(params[:id])
    @user = @product.user_id
    @buy_list_product = BuyListProduct.new
    @review = @product.reviews.new
    @reviews = @product.reviews.where(status: true).page(params[:page]).per(10).reverse_order
  end

  def edit

  end

  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id
    if @product.save
      redirect_to users_product_path(@product), notice: "商品名：#{@product.name}　を作成しました。"
    else
      flash.now[:alert] = '商品登録に失敗しました。内容に誤りがあります'
      render "new"
    end
  end

  def update
    if @product.update(product_params)
      redirect_to users_product_path(@product), notice: "商品情報が更新されました。"
    else
      flash.now[:alert] = '商品更新に失敗しました。内容に誤りがあります'
      render "edit"
    end
  end

    private

    def set_search
      @genres = Genre.where(status: true)
      @q = Product.ransack(params[:q])
    end

    def set_user
      @product = Product.find(params[:id])
      @user = @product.user
      if current_user.id != @user.id
        redirect_to users_products_path, alert: "作成者以外はアクセス権がありません。"
      end
    end

    def product_params
      params.require(:product).permit(:genre_id, :name, :image, :introduction, :jan_code, :user_id, :status)
    end

end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/reviews_controller.rb
class Users::ReviewsController < ApplicationController
  before_action :authenticate_user!

  def create
    @review = current_user.reviews.new(review_params)
    @product = Product.find(params[:review][:product_id])
    @reviews = @product.reviews.where(status: true).page(params[:page]).per(10).reverse_order
    if @review.comment.present? || @review.score.blank?
      @review.score = comment_check
    end
    @review.save
  end


  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_back(fallback_location: root_path)
  end

  private

  def review_params
    params.require(:review).permit(:user_id, :product_id, :score, :comment)
  end

  # Google Natural Language APIの点数を基に、スコアの点数を決める
  def comment_check
    case Language.get_data(review_params[:comment])
    when -1.0..-0.6
      1
    when -0.5..-0.2
      2
    when -0.1..0.1
      3
    when 0.2..0.5
      4
    when 0.6..1.0
      5
    end
  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/users_controller.rb
class Users::UsersController < ApplicationController
  before_action :set_user
  before_action :authenticate_user!


  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to users_user_path(@user), notice:"会員情報が変更されました"
    else
      render 'edit'
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
    # ログイン中会員とページURLの会員idが一致しない場合、元のページへリダイレクト
    if current_user.id != @user.id
      flash[:notice] = "別会員ページのため、アクセス権がありません"
      redirect_back(fallback_location: root_path)
    end
  end

  def user_params
    params.require(:user).permit(:email, :user_id, :image, :name, :name_kana, :nickname)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users/buy_list_products_helper.rb
module Users::BuyListProductsHelper
end

app/helpers/users/buy_lists_helper.rb
module Users::BuyListsHelper
end

app/helpers/users/favorites_helper.rb
module Users::FavoritesHelper
end

app/views/users/buy_lists/index.html.erb
<div class="container">
  <div class="row">
    <h2 class="user-title">買い物リスト</h2>
  </div>

  <div class="row">
    <div class="title-create">
      <%= form_for [:users, @new_buy_list] do |f| %>
      <div class="form-inline">
        <%= render 'layouts/error_messages', model: f.object %>
        <%= f.label :title, "新規買い物リスト作成：" %>
        <%= f.text_field :title, class: "form-control title-create__field" %>
        <%= f.submit "作成", class: "btn btn-success" %>
      </div>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-5 mx-auto">
      <table class="table">
        <thead>
          <tr>
            <th>買い物リスト名</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @buy_lists.each do |buy_list| %>
          <tr>
            <td><%= link_to buy_list.title, users_buy_list_path(buy_list) %></td>
            <td><%= link_to "削除する", users_buy_list_path(buy_list), method: :delete, class: "btn btn-danger float-right", data: {confirm: "削除してもよろしいですか？"} %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/buy_lists/show.html.erb
<div class="container">
  <div class="row">
    <h2 class="user-title">【<%= @buy_list.title %>】の商品</h2>
  </div>

  <div class="row title-create">
    <div class="title-create">
      <%= form_for [:users, @buy_list] do |f| %>
      <div class="form-inline">
        <%= render 'layouts/error_messages', model: f.object %>
        <%= f.label :title, "買い物リスト名変更：" %>
        <%= f.text_field :title, class: "form-control title-create__field" %>
        <%= f.submit "変更", class: "btn btn-primary" %>
      </div>
      <% end %>
    </div>
  </div>

  <div class="row">
    <% if @buy_list_products.present? %>
    <table class="table">
      <thead>
        <tr>
          <th></th>
          <th colspan="2">リスト商品</th>
          <th class="th-width ">個数</th>
          <th class="th-width">消費日数（／個）</th>
          <th class="text-center">購入期限</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @buy_list_products.each do |list| %>
        <tr>
          <%= form_for [:users, list] do |f| %>
          <td>
            <%= f.button :type => "submit", style: 'border-style: none; background:none;' do %>
            <i class='far fa-check-square'></i>
            <% end %>
          </td>
          <td><%= attachment_image_tag list.product, :image, :fill, 50, 50, fallback: "no_image.jpg", size: '50x50' %></td>
          <td><%= link_to list.product.name, users_product_path(list.product) %></td>
          <td class="form-group">
            <%= f.select :amount,(1..10).to_a, {}, class: "form-control" %>
          </td>
          <td class="form-group">
            <%= f.text_field :cost, class: "form-control" %>
          </td>
          <td class="text-center">
            <% if list.cost.blank? && list.dead_line.blank? %>
            <p>初回購入品</p>
            <% elsif list.cost.blank? %>
            <%= list.updated_at.strftime("%Y/%m/%d") %>
            <p>※前回購入日</p>
            <% else %>
            <%= list.dead_line.strftime("%Y/%m/%d") %>
            <% end %>
            <%# 消費日数、購入期限の有無で表示の分岐 %>
          </td>
          <% end %>
          <td><%= link_to " 削除", users_buy_list_product_path(list), method: :delete, class: "btn btn-danger fas fa-trash-alt", data: {confirm: "削除してもよろしいですか？"} %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <% else %>
    <h3 class="mx-auto">
      登録されている商品がありません。<br>
      商品ページから追加してみましょう
    </h3>
    <% end %>
  </div>
</div>