config/routes.rb
Rails.application.routes.draw do

  root 'users/homes#top'

  devise_for :admins, controllers: {
    sessions: "admins/sessions"
  }
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }

  namespace :admins do
    resources :products, only: [:index, :edit, :update, :destroy]
    get '', to: 'products#top'
    resources :genres, only: [:index, :create, :edit, :update]
    resources :reviews, only: [:index, :update]
    resources :users, only: [:index, :show, :edit, :update]
    get "products_search/:id", to: "products#search", as:"products_search"
  end

  namespace :users do
    resources :buy_lists, only: [:index, :show, :create, :update, :destroy]
    resources :buy_list_products, only: [:create, :update, :destroy]
    resources :products, only: [:new, :index, :show, :edit, :create, :update, :destroy] do
      resource :favorites, only: [:create, :destroy]
    end
    resources :reviews, only: [:create, :destroy]
    resources :users, only: [:show, :edit, :update]
    resources :favorites, only: [:index]
    get "guide", to: 'homes#guide'
  end


end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buy_list.rb
class BuyList < ApplicationRecord

  belongs_to :user
  has_many :buy_list_products, dependent: :destroy

  # ユーザーが作成できる買い物リスト名は空欄にできない + 一意性を設定
  validates :title, presence: true, uniqueness: { scope: :user_id }

end

app/models/buy_list_product.rb
class BuyListProduct < ApplicationRecord

  belongs_to :buy_list
  belongs_to :product

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :product

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :products, dependent: :destroy

  validates :title, presence: true

end

app/models/product.rb
class Product < ApplicationRecord

  belongs_to :genre
  belongs_to :user
  has_many :buy_list_products, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :reviews, dependent: :destroy
  attachment :image

  validates :name, presence: true

  def favorited_by?(user)
    Favorite.where(user_id: user.id).exists?
  end

end

app/models/review.rb
class Review < ApplicationRecord

  belongs_to :user
  belongs_to :product

  validates :score, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1
  }, presence: true
  # 属性は数字のみ(1以上〜5以下)と制限

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

  has_many :buy_lists, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :products, dependent: :destroy
  attachment :image

  validates :name, presence: true
  validates :name_kana, presence: true,
                format: {
                  with: /\A[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+\z/,
                  message: "は全角カタカナのみで入力して下さい"
                }
  validates :nickname, presence: true

end

app/controllers/admins/genres_controller.rb
class Admins::GenresController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_genres, only: [:index, :create]

  def index
  end

  def create
    genre = Genre.new(genre_params)
    if genre.save
      redirect_to admins_genres_path
    else
      flash.now[:alert] = 'ジャンル名が空欄です'
      render "index"
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    genre = Genre.find(params[:id])
    if genre.update(genre_params)
      redirect_to admins_genres_path
    else
      @genre = Genre.find(params[:id])
      flash.now[:alert] = 'ジャンル名が空欄です'
      render "edit"
    end
  end

  private


  def genre_params
    params.require(:genre).permit(:title, :status)
  end

  def set_genres
    @q = Genre.ransack(params[:q])
    @genres = @q.result(distinct: true).page(params[:page]).per(20)
    @new_genre = Genre.new
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permited_parameters, if: :devise_controller?

  protected

  def configure_permited_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :name_kana, :nickname])
  end

  def after_sign_in_path_for(resource)
    if resource.instance_of?(Admin)
      admins_path
    elsif resource.instance_of?(User)
      users_buy_lists_path
    end
  end

  def after_sign_out_path_for(resource)
    if resource == :user
      root_path
    elsif resource == :admin
      new_admin_session_path
    end
  end

end

app/controllers/users/homes_controller.rb
class Users::HomesController < ApplicationController
  def top

  end

  def guide

  end

end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users/buy_lists_helper.rb
module Users::BuyListsHelper
end

app/helpers/users/favorites_helper.rb
module Users::FavoritesHelper
end

app/helpers/users/homes_helper.rb
module Users::HomesHelper
end

app/helpers/users/products_helper.rb
module Users::ProductsHelper
end

app/helpers/users/reviews_helper.rb
module Users::ReviewsHelper
end

app/helpers/users/users_helper.rb
module Users::UsersHelper
end

app/views/admins/genres/edit.html.erb
<div class="container-fluid">

  <div class="row">
    <h2 class="admin-title">ジャンル編集</h2>
  </div>

  <div class="row">
    <div class="genre-update">
      <%= form_with model: @genre, url: admins_genre_path, local: true do |f| %>
      <div class="form-inline">
        <%= render 'layouts/error_messages', model: f.object %>
        <%= f.label :title, "ジャンル名：", class: "genre-update__list" %>
        <%= f.text_field :title, class: "genre-update__list form-control"  %>
        <div class="form-check-inline">
          <%= f.radio_button :status, :true, class: "genre-update__list form-check-input"  %>
          <%= f.label :status, "有効", class: "genre-update__list form-check-label"  %>
          <%= f.radio_button :status, :false, class: "genre-update__list form-check-input"  %>
          <%= f.label :status, "無効", class: "genre-update__list form-check-label"  %>
        </div>
        <%= f.submit "更新する", class: "btn btn-primary" %>
      </div>
      <% end %>
    </div>
  </div>

</div>

app/views/admins/genres/index.html.erb
<div class="container-fluid">

  <div class="row">
    <h2 class="admin-title">ジャンル一覧</h2>
  </div>

  <div class="row">
    <div class="genre-create">
      <%= form_for [:admins, @new_genre] do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <%= f.text_field :title, class: "genre-create__list" %>
      <%= f.radio_button :status, :true, checked: true, class: "genre-create__list" %>
      <%= f.label :status, "有効", class: "genre-create__list" %>
      <%= f.radio_button :status, :false, checked: false, class: "genre-create__list" %>
      <%= f.label :status, "無効", class: "genre-create__list" %>
      <%= f.submit "追加", class:"btn btn-primary" %>
      <%end%>
    </div>
  </div>

  <div class="row">
    <div class="genre-list">
      <table class="table">
        <thead>
          <tr>
            <th class="genre-list__column"><%= sort_link(@q, :title, "ジャンル名") %></th>
            <th class="genre-list__column"><%= sort_link(@q, :status, "ステータス") %></th>
            <th class="genre-list__column"><%= sort_link(@q, :updated_at, "更新日") %></th>
            <th class="genre-list__column"></th>
          </tr>
        </thead>
        <tbody>
          <% @genres.each do |genre| %>
          <tr>
            <td><%= genre.title %></td>
            <td><%= genre.status ? "有効" : "無効" %></td>
            <td><%= genre.updated_at.strftime("%Y/%m/%d") %></td>
            <td><%= link_to "編集する", edit_admins_genre_path(genre.id), class: "btn btn-primary" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <%= paginate @genres, class: "paginate" %>
</div>